from bs4 import BeautifulSoup
import newspaper
import nltk
from nltk.tokenize import sent_tokenize
import os
import re
import requests
import spacy
import tldextract
import wikipedia
import wikipediaapi
import tldextract

# Route nltk data path
nltk.data.path.append('/tmp/')

# Define list of non-trusted sources
# Includes social media sites and sources from "False, Misleading, Clickbait-y,
# and Satirical ‘News’ Sources", compiled by Melissa Zimdars available at:
# https://docs.google.com/document/
# d/10eA5-mCZLSS4MQY5QGb5ewC3VAL6pLkT53V_81ZyitM/preview
untrusted_sources = ['100percentfedup',
                     '16wmpo',
                     '21stcenturywire',
                     '24newsflash',
                     '24wpn',
                     '365usanews',
                     '4threvolutionarywar',
                     '70news',
                     '82.221.129.208',
                     'acting-man',
                     'alt-market',
                     'americankabuki',
                     'ammoland',
                     'amposts',
                     'automaticearth',
                     'bb4sp',
                     'badsquad',
                     'boilingfrogspost',
                     'brotherjohnf',
                     'bullionbullscanada',
                     'cnsnews',
                     'comingdepression',
                     'diyhours',
                     'dprogram',
                     'davejanda',
                     'deadlinelive',
                     'deadlyclear',
                     'dollarvigilante',
                     'donaldtrumppotus45',
                     'dont-tread-on',
                     'dutchsinse',
                     'eutimes',
                     'eaglerising',
                     'ebolahoax',
                     'empirehearland',
                     'emptywheel',
                     'experimentalvaccines',
                     'expose1933',
                     'farmwars',
                     'financialsurvivalnetwork',
                     'freebeacon',
                     'freedomforceinternational',
                     'freedomsphoenix',
                     'globaleconomicanalysis',
                     'gonzalolira',
                     'greenmedinfo',
                     'itccs',
                     'itmakessenseblog',
                     'kmt11',
                     'mad-yet',
                     'nationalufocenter',
                     'newsbuster',
                     'newsmax',
                     'nomorefakenews',
                     'notime4bull',
                     'nutritionalanarchy',
                     'occupy',
                     'offgridsurvival',
                     'politcalpiehole',
                     'politicalpiehole',
                     'politicaltracker',
                     'publicintelligence',
                     'redicecreations',
                     'rightsidenews',
                     'sjlendman',
                     'srsroccoreport',
                     'stawealth',
                     'shadowstats',
                     'silver-coin-investor',
                     'silverbearcafe',
                     'silverdoctors',
                     'silverstealers',
                     'sovereignman',
                     'stevequayle',
                     'survivalblog',
                     'survivalknowhow',
                     'tdtalliance',
                     'tenthamendmentcenter',
                     'theaureport',
                     'thebricspost',
                     'thebrowser',
                     'theburningplatform',
                     'thecrowehouse',
                     'thedailycoin',
                     'thedailycrux',
                     'theextinctionprotocol',
                     'thenewsfile',
                     'theoutsiderclub',
                     'thepeoplesvoice',
                     'thetruthwins',
                     'thevictoryreport',
                     'thewealthwatchman',
                     'tomwoods',
                     'tragedyandhope',
                     'trueactivist',
                     'truthinmedia',
                     'truthstreammedia',
                     'usawatchdog',
                     'wallstreetonparade',
                     'wideawakenews',
                     'williambanzai7',
                     'willyloman',
                     'wolfstreet',
                     'x22report',
                     'youngcons',
                     'yournewsline',
                     'zengardner',
                     'aanirfan',
                     'abcnewsgo',
                     'abeldanger',
                     'abovetopsecret',
                     'abriluno',
                     'aceflashman',
                     'actforamerica',
                     'activistpost',
                     'actualidadpanamericana',
                     'addictinginfo',
                     'adflegal',
                     'adobochronicles',
                     'aheadoftheherd',
                     'ahtribune',
                     'allnewspipeline',
                     'alternativemediasyndicate',
                     'americablog',
                     'americanborderpatrol',
                     'americanfreepress',
                     'americanlookout',
                     'americannews',
                     'americannewsx',
                     'americanoverlook',
                     'americanpatriotdaily',
                     'americanpoliticnews',
                     'americanpresident',
                     'americanreviewer',
                     'americanthinker',
                     'americantoday',
                     'americasfreedomfighters',
                     'amplifyingglass',
                     'amren',
                     'amtvmedia',
                     'amusmentic',
                     'ancient-code',
                     'anews24',
                     'angrypatriotmovement',
                     'anonews',
                     'anonhq',
                     'anonjekloy',
                     'anonnews',
                     'anotherdayintheempire',
                     'answers',
                     'antiwar',
                     'antoniusaquinas',
                     'arxiv',
                     'aryannationswordwide1488',
                     'asia-pacificresearch',
                     'assassinationscience',
                     'associatedmediacoverage',
                     'attn',
                     'aurora-news',
                     'automotostar',
                     'awarenessact',
                     'awazetribune',
                     'awdnews',
                     'awm',
                     'baptistnews',
                     'barenakedislam',
                     'barnesreview',
                     'beehivebugle',
                     'beforeitsnews',
                     'betootaadvocate',
                     'bients',
                     'bigamericannews',
                     'bigbluedimension',
                     'bigbluevision',
                     'bighairynews',
                     'bignuggetnews',
                     'bigpzone',
                     'bipartisanreport',
                     'blackagendareport',
                     'blackgenocide',
                     'blackinusrancenews',
                     'blacklistednews',
                     'blogger',
                     'blogspot',
                     'bluenationreview',
                     'borowitzreport',
                     'bostonleader',
                     'bostontribune',
                     'breaking911',
                     'breakpoint',
                     'breitbart',
                     'burrardstreetjournal',
                     'buzzfeedusa',
                     'bvanews',
                     'callthecops',
                     'canadafreepress',
                     'cannasos',
                     'cap-news',
                     'celebtricity',
                     'centerforsecuritypolicy',
                     'channel-7-news',
                     'channel18news',
                     'charismanews',
                     'chaser',
                     'checkoutthehealthyworld',
                     'chicksontheright',
                     'christianfightback',
                     'christianpost',
                     'christiantimesnewspaper',
                     'christwire',
                     'chronicle',
                     'chroniclesmagazine',
                     'citizensunited',
                     'city-journal',
                     'cityworldnews',
                     'civictribune',
                     'clashdaily',
                     'clickhole',
                     'cnnews3',
                     'cnnnext',
                     'coasttocoastam',
                     'coed',
                     'collective-evolution',
                     'collectivelyconscious',
                     'commentarymagazine',
                     'commondreams',
                     'concisepolitics',
                     'consciouslifenews',
                     'conservapedia',
                     'conservativebyte',
                     'conservativedailypost',
                     'conservativefighters',
                     'conservativefiringline',
                     'conservativeflashnews',
                     'conservativefrontline',
                     'conservativeheadlines',
                     'conservativehq',
                     'conservativeinfidel',
                     'conservativeoutfitters',
                     'conservativepapers',
                     'conservativerefocus',
                     'conservativereview',
                     'conservativespirit',
                     'conservativestate',
                     'conservativetribune',
                     'consortiumnews',
                     'conspiracyplanet',
                     'conspiracywire',
                     'corbettreport',
                     'countdowntozerotime',
                     'countercurrentnews',
                     'countercurrents',
                     'counterinformation',
                     'counterjihad',
                     'counterpsyops',
                     'counterpunch',
                     'cowgernation',
                     'creambmp',
                     'creativitymovement',
                     'cryptogon',
                     'crystalair',
                     'dailybuzzlive',
                     'dailycaller',
                     'dailycurrant',
                     'dailydiscord',
                     'dailyheadlines',
                     'dailyinfobox',
                     'dailyken',
                     'dailykos',
                     'dailyleak',
                     'dailynews10',
                     'dailynews5',
                     'dailynewsbin',
                     'dailynewspolitic',
                     'dailynewsposts',
                     'dailyoccupation',
                     'dailypolitics',
                     'dailypoliticsusa',
                     'dailysignal',
                     'dailysnark',
                     'dailysquib',
                     'dailystormer',
                     'dailysurge',
                     'dailytelegraph',
                     'dailyusaupdate',
                     'dailywire',
                     'damnleaks',
                     'dandygoat',
                     'darkmoon',
                     'darkpolitricks',
                     'dataasylum',
                     'davidduke',
                     'davidstockmanscontracorner',
                     'davidwolfe',
                     'dcclothesline',
                     'dcgazette',
                     'dcleaks',
                     'ddemocraticunderground',
                     'debunkingskeptics',
                     'defenddemocracy',
                     'delectabledietofpics',
                     'dennismichaellynch',
                     'denverguardian',
                     'departed',
                     'departedmedia',
                     'der-postillon',
                     'derfmagazine',
                     'dineal',
                     'disclose',
                     'disclosuremedia',
                     'dissentmagazine',
                     'diversitychronicle',
                     'donaldtrumpnews',
                     'downtrend',
                     'drrichswier',
                     'drudgereport',
                     'duffleblog',
                     'duhprogressive',
                     'economicnoise',
                     'ecowatch',
                     'educate-yourself',
                     'educateinspirechange',
                     'electionnightgatekeepers',
                     'elelephantintheroom',
                     'elitereaders',
                     'elkoshary',
                     'elmundotoday',
                     'embols',
                     'empireherald',
                     'empirenews',
                     'empiresports',
                     'en-vovle',
                     'enabon',
                     'endingthefed',
                     'endoftheamericandream',
                     'endtime',
                     'enduringvision',
                     'english',
                     'enhlive',
                     'eutopia',
                     'everydayworldnews',
                     'everythingnewdaily',
                     'ewao',
                     'express',
                     'extraclubmagazine',
                     'eyeopening',
                     'facebook',
                     'fakingnews',
                     'familysecuritymatters',
                     'fantasticword',
                     'federalistpress',
                     'fedsalert',
                     'fellowshipoftheminds',
                     'filmsforaction',
                     'firearmscoalition',
                     'flashnewscorner',
                     'floridasunpost',
                     'flyheight',
                     'fmobserver',
                     'fognews',
                     'foodbabe',
                     'foreignpolicyjournal',
                     'fort-russ',
                     'fourwinds10',
                     'fprnradio',
                     'freakoutnation',
                     'freedomdaily',
                     'freedomoutpost',
                     'freedomworks',
                     'freedomworldnews',
                     'freepatriot',
                     'freewoodpost',
                     'freshdailyreport',
                     'fridaymash',
                     'fromthetrenchesworldreport',
                     'frontpagemag',
                     'gaia',
                     'galacticconnection',
                     'gangstergovernment',
                     'gatesofvienna',
                     'geoengineeringwatch',
                     'geopolmonitor',
                     'givemeliberity01',
                     'glaringhypocrisy',
                     'globalpoliticsnow',
                     'globalresearch',
                     'glossynews',
                     'godlikeproductions',
                     'gomerblog',
                     'goneleft',
                     'google',
                     'gopthedailydose',
                     'govtslaves',
                     'greanvillepost',
                     'guardianlv',
                     'guccifer2',
                     'gulagbound',
                     'gummypost',
                     'hangthebankers',
                     'healthimpactnews',
                     'healthnutnews',
                     'healthy-holistic-living',
                     'healthycareandbeauty',
                     'healthyworldhouse',
                     'heartland',
                     'heatst',
                     'henrymakow',
                     'heresyblog',
                     'heritage',
                     'holyobserver',
                     'horowitzfreedomcenter',
                     'humansarefree',
                     'humortimes',
                     'huzlers',
                     'icr',
                     'ifyouonlynews',
                     'igrewupinusa',
                     'ihavethetruth',
                     'ihr',
                     'ijr',
                     'illuminati-news',
                     'ilovemyfreedom',
                     'immediatesafety',
                     'in5d',
                     'indiaarising',
                     'infiniteunknown',
                     'informationclearinghouse',
                     'informetoday',
                     'infostormer',
                     'infowars',
                     'instaworldnews',
                     'intellihub',
                     'interestingdailynews',
                     'intrendtoday',
                     'intrepidreport',
                     'investmentresearchdynamics',
                     'investmentwatchblog',
                     'ironictimes',
                     'islamicanews',
                     'itaglive',
                     'iwanttoexplore',
                     'jackpineradicals',
                     'jacobinmag',
                     'jamesrgrangerjr',
                     'jesus-is-savior',
                     'jewsnews',
                     'jihadwatch',
                     'johnnyrobish',
                     'jonesreport',
                     'journal-neo',
                     'judicialwatch',
                     'katehon',
                     'kauilapele',
                     'kingworldnews',
                     'knowledgeoftoday',
                     'konkonsagh',
                     'krbcnews',
                     'ky12news',
                     'ladylibertynews',
                     'landoverbaptist',
                     'lastdeplorables',
                     'learnprogress',
                     'legorafi',
                     'lewrockwell',
                     'liberalamerica',
                     'liberalbias',
                     'liberaldarkness',
                     'liberalplug',
                     'libertyalliance',
                     'libertyblitzkrieg',
                     'libertyfederation',
                     'libertymovementradio',
                     'libertynews',
                     'libertytalk',
                     'libertyunyielding',
                     'libertyvideos',
                     'libertywritersnews',
                     'lifeandabout',
                     'lifenews',
                     'lifeprevention',
                     'lifesitenews',
                     'lifezette',
                     'lightlybraisedturnip',
                     'linkedin',
                     'liveactionnews',
                     'livefreelivenatural',
                     'livejournal',
                     'livevote',
                     'loanpride',
                     'local31news',
                     'lovethispic',
                     'lushforlife',
                     'madpatriots',
                     'madworldnews',
                     'magafeed',
                     'maganews',
                     'majorthoughts',
                     'makeamericagreattoday',
                     'meanlefthook',
                     'mediamass',
                     'mediazone',
                     'megafreshnews',
                     'megynkelly',
                     'mentor2day',
                     'metropolitanworlds',
                     'militianews',
                     'mintpressnews',
                     'molonlabemedia',
                     'moonofalabama',
                     'morningledger',
                     'morningnewsusa',
                     'mpidailymagazine',
                     'mrc',
                     'mrconservative',
                     'mydailyrelaxation',
                     'myfreshnews',
                     'myzonetoday',
                     'nahadaily',
                     'nakedcapitalism',
                     'nasamoonhoax',
                     'nationalreport',
                     'nationalreview',
                     'nationalvanguard',
                     'nationindistress',
                     'nationonenews',
                     'naturalblaze',
                     'naturalnews',
                     'naturalnewsblogs',
                     'nbcpolitics',
                     'nbcpoll',
                     'ncscooper',
                     'neonnettle',
                     'nephef',
                     'nevo',
                     'newcenturytimes',
                     'newcoldwar',
                     'newpoliticstoday',
                     'news-hound',
                     'news4ktla',
                     'newsbbc',
                     'newsbiscuit',
                     'newsbreak',
                     'newsbreakers',
                     'newsbreakshere',
                     'newsbysquad',
                     'newscenterusa',
                     'newscorpse',
                     'newsdaily12',
                     'newsexaminer',
                     'newsfrompolitics',
                     'newsleak',
                     'newslo',
                     'newslogue',
                     'newsmagazine',
                     'newsmutiny',
                     'newsninja2012',
                     'newsopening',
                     'newstarget',
                     'newsthump',
                     'newstoad',
                     'newswatch28',
                     'newswatch33',
                     'newswire-24',
                     'newswithviews',
                     'newyorker',
                     'nodisinfo',
                     'nonaiswa',
                     'northcrane',
                     'notallowedto',
                     'now8news',
                     'nowtheendbegins',
                     'npiamerica',
                     'nutritionfacts',
                     'nymeta',
                     'nyuzer',
                     'oathkeepers',
                     'objectiveministries',
                     'observatorial',
                     'observer',
                     'occupydemocrats',
                     'occupyliberals',
                     'odgossip',
                     'off-guardian',
                     'oftwominds',
                     'oilgeopolitics',
                     'onepoliticalplaza',
                     'onlineconservativepress',
                     'opednews',
                     'openmagazines',
                     'openmindmagazine',
                     'orientalreview',
                     'other98',
                     'pakalertpress',
                     'palmerreport',
                     'pamelageller',
                     'patdollar',
                     'patriotarchives',
                     'patriotchronicle',
                     'patriotnewsdaily',
                     'patriotpost',
                     'patriotrising',
                     'patriotupdate',
                     'paulcraigroberts',
                     'pinterest',
                     'pjmedia',
                     'platosguns',
                     'policestateusa',
                     'policyreview',
                     'politicalblindspot',
                     'politicalcult',
                     'politicalears',
                     'politicalo',
                     'politicalsitenews',
                     'politicaltimes',
                     'politicalupdator',
                     'politicono',
                     'politicops',
                     'politicot',
                     'politicsbreaking',
                     'politicsinformation',
                     'politicsinfotoday',
                     'politicsintheusa',
                     'politicsinusa',
                     'politicsusanews',
                     'politicususa',
                     'pollhype',
                     'powerlineblog',
                     'powerpoliticians',
                     'pravda',
                     'pravdareport',
                     'prepperwebsite',
                     'president45donaldtrump',
                     'presidentialvoting2016',
                     'press24',
                     'presstv',
                     'prisonplanet',
                     'prntly',
                     'proamericanews',
                     'progressivestoday',
                     'projectveritas',
                     'proudcons',
                     'proudemocrat',
                     'qpolitical',
                     'quora',
                     'randpaulreview',
                     'rawforbeauty',
                     'rawstory',
                     'rawws',
                     'rbth',
                     'react365',
                     'readconservatives',
                     'readynutrition',
                     'reagancoalition',
                     'realfarmacy',
                     'realnewsrightnow',
                     'realplanetnews',
                     'realprogress',
                     'realtimepolitics',
                     'redcountry',
                     'reddit',
                     'redflagnews',
                     'redrocktribune',
                     'redstate',
                     'redstatewatcher',
                     'reductress',
                     'regated',
                     'religionlo',
                     'religionmind',
                     'remedydaily',
                     'rense',
                     'resistancereport',
                     'responsibletechnology',
                     'returnofkings',
                     'revolutions2040',
                     'rhotv',
                     'rickwells',
                     'rightalert',
                     'righton',
                     'rightwingnews',
                     'rilenews',
                     'rinf',
                     'rockcitytimes',
                     'rogue-nation3',
                     'ronpaulinstitute',
                     'rt',
                     'rumorjournal',
                     'rumormillnews',
                     'ruptly',
                     'russia-direct',
                     'russia-insider',
                     'satiratribune',
                     'satirewire',
                     'scrappleface',
                     'scribd',
                     'secretsofthefed',
                     'sensationalisttimes',
                     'sentinelblog',
                     'sgtreport',
                     'shadowproof',
                     'shareblue',
                     'sheepkillers',
                     'shiftfrequency',
                     'shoebat',
                     'shtfplan',
                     'silentmajoritypatriots',
                     'skeptiko',
                     'smag31',
                     'smartknowledgeu',
                     'socialeverythings',
                     'solari',
                     'sonsoflibertyradio',
                     'sott',
                     'sourceplanet',
                     'southfront',
                     'southweb',
                     'speciallifeentertainment',
                     'speld',
                     'spinzon',
                     'sportspickle',
                     'sputniknews',
                     'stackexchange',
                     'statenation',
                     'stneotscitizen',
                     'stormcloudsgathering',
                     'strategic-culture',
                     'stuppid',
                     'subjectpolitics',
                     'success-street',
                     'suggesthealthytips',
                     'superstation95',
                     'supremepatriot',
                     'surenews',
                     'surrealscoop',
                     'survivopedia',
                     'szandorblestman',
                     'tap-news',
                     'tdnewswire',
                     'teaparty',
                     'teapartyeconomist',
                     'teapartytribune',
                     'tellmenow',
                     'thatviralfeed',
                     'the-insider',
                     'the-newspapers',
                     'theamericancause',
                     'theamericanindependent',
                     'theamericanmirror',
                     'theantimedia',
                     'theautogear',
                     'thebeaverton',
                     'thebigriddle',
                     'theblaze',
                     'thebostontribune',
                     'thecarsmagazine',
                     'thecivilian',
                     'thecommonsenseshow',
                     'theconservativetreehouse',
                     'thecontroversialfiles',
                     'thedailybeast',
                     'thedailybell',
                     'thedailymash',
                     'thedailysheeple',
                     'thedailywtf',
                     'thedemocratic',
                     'theduran',
                     'theearthchild',
                     'theeconomiccollapseblog',
                     'theeventchronicle',
                     'thefederalistpapers',
                     'thefifthcolumnnews',
                     'theforbiddenknowledge',
                     'thefreepatriot',
                     'thefreethoughtproject',
                     'thegatewaypundit',
                     'thegoldandoilguy',
                     'thegoldwater',
                     'thehardtimes',
                     'theineptowl',
                     'theinformedamerican',
                     'theintercept',
                     'theinternetpost',
                     'thelastgreatstand',
                     'thelastlineofdefense',
                     'thelibertybeacon',
                     'thelibertymill',
                     'themadisonmisnomer',
                     'themideastbeast',
                     'themindunleashed',
                     'themoralofthestory',
                     'themuslimissue',
                     'thenet24h',
                     'thenewamerican',
                     'thenewinquiry',
                     'thenewsdoctors',
                     'thenewsnerd',
                     'thenewyorkevening',
                     'theonion',
                     'theopenscroll',
                     'theorganicprepper',
                     'theoxymoron',
                     'thepeoplescube',
                     'thephaser',
                     'thepoke',
                     'thepoliticalcesspool',
                     'thepoliticalinsider',
                     'thepostemail',
                     'theracketreport',
                     'therealstrategy',
                     'therebel',
                     'thereporterz',
                     'therightists',
                     'therightplanet',
                     'therightscoop',
                     'therightstuff',
                     'therundownlive',
                     'therussophile',
                     'thesaker',
                     'theseattletribune',
                     'theshovel',
                     'theskunk',
                     'thesleuthjournal',
                     'thespoof',
                     'thestatelyharold',
                     'thetimesoftheworld',
                     'thetrumpmedia',
                     'thetruthaboutcancer',
                     'thetruthdivision',
                     'thetruthseeker',
                     'theunrealtimes',
                     'theusa-news',
                     'theuspatriot',
                     'thevalleyreport',
                     'thewashingtonpress',
                     'thewatchtowers',
                     'theworldstyle',
                     'thinkprogress',
                     'thirdworldtraveler',
                     'thisismynewworld',
                     'threepercenternation',
                     'thrivemovement',
                     'times',
                     'tmzworldnews',
                     'topekasnews',
                     'topinfopost',
                     'topnewspolitics',
                     'topratedviral',
                     'toprightnews',
                     'totalworldnews',
                     'traderdan',
                     'tradewithdave',
                     'trendingnewsguide',
                     'trendingnewstoday',
                     'tribuneherald',
                     'tribunist',
                     'trueamericans',
                     'trueeconomics',
                     'truepundit',
                     'truetrumpers',
                     'trumpvision365',
                     'trunews',
                     'truthandaction',
                     'truthbroadcastnetwork',
                     'truthfeed',
                     'truthfrequencyradio',
                     'truthingold',
                     'truthkings',
                     'truthnetwork',
                     'truthrevolt',
                     'tunerspeed',
                     'turnerradionetwork',
                     'twitchy',
                     'twitter',
                     'tyronetribulations',
                     'ufoholic',
                     'unclesamsmisguidedchildren',
                     'unconfirmedsources',
                     'undergroundhealth',
                     'undergroundnewsreport',
                     'undergroundworldnews',
                     'unionleader',
                     'unitedmediapublishing',
                     'universepolitics',
                     'unz',
                     'usa-radio',
                     'usa-television',
                     'usa2016elections',
                     'usadailyinfo',
                     'usadailypolitics',
                     'usadailytime',
                     'usadosenews',
                     'usafirstinformation',
                     'usahitman',
                     'usainfobox',
                     'usamagazinestudio',
                     'usanewsflash',
                     'usanewsinsider',
                     'usanewspolitics',
                     'usanewstoday',
                     'usaonlinepolitics',
                     'usaphase',
                     'usapolitics24hrs',
                     'usapoliticsdaily',
                     'usapoliticsnow',
                     'usapoliticstoday',
                     'usapoliticszone',
                     'usapoliticus',
                     'usascan',
                     'usasnich',
                     'usasupreme',
                     'usatoday',
                     'usatodaynews',
                     'usatwentyfour',
                     'uschronicle',
                     'usconservativetoday',
                     'usdefensewatch',
                     'usfanzone',
                     'ushealthyadvisor',
                     'ushealthylife',
                     'usherald',
                     'usinfonews',
                     'uslifetoday',
                     'uspoliticslive',
                     'uspoln',
                     'uspostman',
                     'usuncut',
                     'usviewer',
                     'vdare',
                     'veteransnewsnow',
                     'veteranstoday',
                     'vigilantcitizen',
                     'viralactions',
                     'viralliberty',
                     'viraltube',
                     'voxtribune',
                     'wakeupthesheep',
                     'wakingtimes',
                     'wakingupwisconsin',
                     'washingtonexaminer',
                     'washingtonfed',
                     'washingtonsblog',
                     'waterfordwhispersnews',
                     'wealthcycles',
                     'wealthwire',
                     'wearechange',
                     'weaselzippers',
                     'webdaily',
                     'weeklystandard',
                     'weeklyworldnews',
                     'weshapelife',
                     'westernjournalism',
                     'whatdoesitmean',
                     'whatreallyhappened',
                     'whitepower',
                     'whydontyoutrythis',
                     'wideawakeamerica',
                     'wikileaks',
                     'wikipedia',
                     'wikispooks',
                     'winkprogress',
                     'winningdemocrats',
                     'witscience',
                     'wnd',
                     'wonkie',
                     'wordpress',
                     'world24monitor',
                     'worldcallyoutoday',
                     'worlddaily',
                     'worldnewsdailyreport',
                     'worldnewspolitics',
                     'worldpoliticsnow',
                     'worldpoliticsus',
                     'worldrumor',
                     'worldstoriestoday',
                     'worldtruth',
                     'worldwidehealthy',
                     'wtoe5news',
                     'wundergroundmusic',
                     'yellowhammernews',
                     'yesimright',
                     'yourfunpage',
                     'yournationnews',
                     'yournewswire',
                     'youtube',
                     'zaytung',
                     'zerohedge',
                     'zootfeed']


# define Python user-defined exceptions
class Error(Exception):
    """Base class for other exceptions"""
    pass


class NotNewsSiteError(Error):
    """Raised when website is not a major news website"""
    pass


def retrieve_article_details(url):
    """Returns title, summary, and text, given a URL to a news article"""
    # Example input url
    # Prep article
    article = newspaper.Article(url)
    article.download()
    article.parse()
    # Title
    title = article.title
    # Summary
    article.nlp()  # Need to call this first
    summary = article.summary
    # If you need it:
    # Get article text (Note: Sunny removes a bunch of weird characters here,
    # that's what the chain of .replace are)
    encoded_txt = article.text \
        .replace(u'\u2014', '-').replace(u'\u201c', '\"') \
        .replace(u'\u201d', '\"').replace(u'\u2019', "'") \
        .replace("\n", "")
    return title, summary, encoded_txt


def reveal_source(url):
    """Extracts domain names from given URL"""
    # editing cache_file setting
    no_cache_extract = tldextract.TLDExtract(cache_file=False)   
    url_ex = no_cache_extract(url)
    if url_ex.subdomain == "":
        home_page = 'https://' + '.'.join([url_ex.domain, url_ex.suffix])
    else:
        home_page = 'https://' + '.'.join([url_ex.subdomain,
                                           url_ex.domain, url_ex.suffix])

    domain_name = url_ex.domain
    subdomain_name = url_ex.domain

    return home_page, domain_name, subdomain_name


def google_query(query, num_results=10, header={'User-agent': 'your bot 0'}):
    """Pulls all links from first page of Google query"""
    query_str = query.replace(" ", "+")
    query_page = 'https://www.google.com/search?q=' + query_str
    search_page = requests.get(query_page, headers=header)
    search_soup = BeautifulSoup(search_page.text, "html.parser")
    links = search_soup.findAll("a")
    all_links = []
    for link in search_soup.find_all(
            "a", href=re.
            compile("(?<=/url\?q=)(htt.*://.*)"))[0:num_results]:
        all_links.extend(
            re.split(":(?=http)", link["href"].replace("/url?q=", "")))
    return all_links, query_page


def investigate_source(url):
    """Code that investigates source from a article URL website.
    Returns summary about news source (domain) from Wikipedia
    and the news source's own about page.
    """

    # first we extract the domain names
    home_page, domain_name, subdomain_name = reveal_source(url)

    # obtains wikipedia summary
    # searches for subdomain name first
    wiki_search_items = wikipedia.search(
        domain_name) + \
        wikipedia.search(subdomain_name)
    wiki_api = wikipediaapi.Wikipedia('en')
    news_string_list = ['news', 'fake', 'satirical',
                        'satire', 'hoax', 'propaganda',
                        'politics']

    # checks each element found in wiki-search, stops if
    # one wiki-pedia page is news related
    wiki_summary = "Wikipedia page doesn't exist."
    wiki_link = None
    if wiki_search_items:
        for item in wiki_search_items:
            wiki_page = wiki_api.page(item)
            wiki_sum = wiki_page.summary
            wiki_l = wiki_page.fullurl
            if any(word in wiki_sum for word in news_string_list):
                wiki_summary = wiki_sum
                wiki_link = wiki_l
                break

    # variable to specify where the self description comes from
    self_desc_src = "None"

    # Searches for description within the website
    response = requests.get(home_page)
    news_soup = BeautifulSoup(response.text, 'html.parser')
    metas = news_soup.find_all('meta')
    try:
        self_summary = [meta.attrs['content'] for meta in metas if 'name'
                        in meta.attrs and meta.attrs['name'] == 'description']
    except KeyError:
        self_summary = None

    if self_summary:
        self_summary = self_summary[0]
        self_desc_src = "meta"

    # if self_summary is empty, attempt to find an about page
    if not self_summary:
        self_summary = "Description about news source doesn't exist"
        str_to_check = home_page + '/about'
        all_as = news_soup.find_all('a')
        about_page_urls = []
        for a_tag in all_as:
            try:
                if str_to_check in a_tag.attrs['href']:
                    about_page_urls.append(a_tag.attrs['href'])
            except KeyError:
                pass
        for url in about_page_urls:
            about_page = newspaper.Article(url)
            about_page.download()
            about_page.parse()
            abt_pg_txt = about_page.text
            if any(word in abt_pg_txt for word in news_string_list):
                self_summary = about_page.text
                self_desc_src = "about"
                break

    return wiki_link, self_desc_src, wiki_summary, self_summary


def find_better_coverage(url):
    """Returns top 5 Google search results for article topic/claim
    excluding search results from original source's domain and
    untrusted sources
    """
    search_q, _ = trace_claim(url)
    all_links, query_page = google_query(search_q)
    # Remove tracking components after "&" in URL, to allow proper display of
    # Google Search result links
    all_links = [link.split("&")[0] for link in all_links]
    # Filter out results from original URL's source, untrusted sources, and
    # URLs ending in ".com.co"
    url_domain = reveal_source(url)[1]
    exclude_sites = untrusted_sources + [url_domain]
    filtered_links = [link for link in all_links
                      if not any(s in link for s in exclude_sites)]
    filtered_links = [link for link in filtered_links
                      if not reveal_source(link)[0].endswith(".com.co")]
    # If there are fewer than 5 approved results, only those buttons will
    # appear on the front end
    top_5_results = [(link, reveal_source(link)[1])
                     for link in filtered_links][:5]
    # Return top 5 relevant results and Google query page
    return top_5_results, query_page


def trace_claim(url):
    title, summary, encoded_txt = retrieve_article_details(url)
    title = title.replace(";", "")
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(title)
    doc = [token for token in doc if
           not (token.is_stop or token.pos_ in ["PUNCT", "SYM", "ADJ", "ADP"])]
    doc = [token for token in doc if
           token.dep_ in ["nsubj", "compound", "dobj", "pobj"]]
    search_q = " ".join([str(token) for token in doc])
    search_q_google = search_q.replace("+", " ")
    return search_q, search_q_google
